### ISSUE TITLE
Incompatibility with FNA tModLoader 64-bit

### ISSUE THREAD

**Issue by InjuredWolf** [JavidPack/TerraCustom#22]
When trying to use **TerraCustom v0.5.4** with **tModloader v0.10.1.5 - tml FNA 64bit** you get the following error message:

```
System.MissingMethodException: Method not found: 'Void ReLogic.OS.Platform.SetWindowUnicodeTitle(Microsoft.Xna.Framework.GameWindow, System.String)'.
   at Terraria.Main.SetTitle()
   at Terraria.Main.Initialize()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
```

is there a workaround or will I have to wait for an update?
(in theory a potential workaround I might try would be to use a standard tModLoader build to gen the world and then switch to 64bit to play, not yet tested)

**Comment by JavidPack** [comment]
yes, they are incompatible, you would need to switch back to the normal install to get it working. I'm not sure if it would work if you just made a backup of the non-64 version of the install directory, you can try that if you want to switch back and forth more quickly

**Comment by InjuredWolf** [comment]
Any plans to add compatibility? Understandable if you aren't, just curious.

**Comment by JavidPack** [comment]
I can't spend the time to do that, but hopefully the 64 bit version figures things out so that they don't mess with the files in a way that lets it load normally.
