### ISSUE TITLE
Can't find Fonts\Item_Stack even though it exists

### ISSUE THREAD

**Issue by crabnebulakek** [JavidPack/TerraCustom#3]
---------------------------
Terraria: Error
---------------------------
Microsoft.Xna.Framework.Content.ContentLoadException: Error loading "Fonts\Item_Stack". Cannot find ContentTypeReader ReLogic.Graphics.DynamicSpriteFontReader, ReLogic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.

   at Microsoft.Xna.Framework.Content.ContentTypeReaderManager.InstantiateTypeReader(String readerTypeName, ContentReader contentReader, ContentTypeReader& reader)

   at Microsoft.Xna.Framework.Content.ContentTypeReaderManager.GetTypeReader(String readerTypeName, ContentReader contentReader, List`1& newTypeReaders)

   at Microsoft.Xna.Framework.Content.ContentTypeReaderManager.ReadTypeManifest(Int32 typeCount, ContentReader contentReader)

   at Microsoft.Xna.Framework.Content.ContentReader.ReadHeader()

   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]()

   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)

   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName)

   at Terraria.Main.OurLoad[T](String path)

   at Terraria.Main.LoadFonts()

   at Terraria.Main.LoadContent()

   at Microsoft.Xna.Framework.Game.Initialize()

   at Terraria.Main.Initialize()

   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)

   at Terraria.Program.LaunchGame(String[] args)
---------------------------
OK   
---------------------------

I've tried verifying the game cache and reinstalling both TerraCustom and Terraria, but nothing seems to fix this issue. The Item_Stack.xnb  file does exist.

**Comment by JavidPack** [comment]
The current release of TerraCustom relies on 1.3.4.4 being installed. The error you are seeing is due to 1.3.5+ being installed (some dependency files changed) If you manage to downgrade to 1.3.4.4, you can use TerraCustom again.
